### ISSUE TITLE
Twitter Client Submission

### ISSUE THREAD

**Issue by atommarvel** [atommarvel/twitterClone#1]
/cc @codepathreview @codepath @nidhi1608

**Comment by codepathreview** [comment]
:+1: Congrats on completing the project! Nice work overall.

* Good work on clean UI.
* Good to see you were able to format the timestamp cleanly
* Good to see you refreshed the timeline after composing a new tweet
* Good to see you added ActiveAndroid annotations to the models
* Consider adding [progress bars] (http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out
* Consider adding pull to refresh for the home timeline

I have provided a detailed [Twitter Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, Models, Authentication, API Communication, Preferences, ActionBar, et al) and see how they all fit together.
